#pragma once

#define ASSET_PATH "assets\\"
#define WINDOW_WIDTH 750
#define WINDOW_HEIGHT 950
#define CANVAS_WIDTH 1200
#define CANVAS_HEIGHT 1500
#define PLAYER_WIDTH 260
#define PLAYER_HEIGHT 20
#define BALL_WIDTH 60
#define BALL_HEIGHT 60
#define BALL_RADIUS 25
#define OBSTACLE_WIDTH 300
#define OBSTACLE_HEIGHT 70
#define OBSTACLE_INVERT_WIDTH 70
#define OBSTACLE_INVERT_HEIGHT 300
